### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by victorvhpg** [jnwon/VocaloidTTS#1]
Are possible create an audio file through code ?
Input: some text
Output: audio file

**Comment by jnwon** [comment]
Thank you for your interest to this program.
Unfortunately this is not a stand alone program but an add-on plugin to Vocaloid editor.
If you want to create an audio file from the program, register this plugin(.lua file) to the Vocaloid editor first and input texts you want to convert to an audio file after running the added plugin. Then run the WAV exporting feature of the Vocaloid editor.

Here's a demo video of usage: [https://www.nicovideo.jp/watch/sm38950276](https://www.nicovideo.jp/watch/sm38950276)
There is a download link for the plugin package in the video description!

**Comment by victorvhpg** [comment]
Thanks
