### ISSUE TITLE
VocaloidTTS refuses to function

### ISSUE THREAD

**Issue by yotsuuba** [jnwon/VocaloidTTS#2]
I am running Windows 10 x64

I am using Vocaloid 4

The singer has been set, and I am using Iroha_V4

When entering " はじめまして、 いろは と もうします" I am greeted with the following error
![image](https://github.com/jnwon/VocaloidTTS/assets/43102583/10f68a8e-f825-42b4-891c-60b5657d31c7)

I have followed the setup file closely, Is there anything I am missing?

**Comment by jnwon** [comment]
Thank you for using Vocaloid TTS.

That error occurs because the inputed sentence has vacant space characters between some characters.
Basically in grammar of Japanese language people don't use vacant space when they write a sentence, so this plug in was also programmed based on that rule.

Try your sentence again, after removing all vacant space characters: such as "はじめまして、いろはともうします"

**Comment by jnwon** [comment]
@yotsuuba Also, please check your System locale in Control panel, whether it is Japanese or not. To run Vocaloid TTS correctly the system locale must be set with Japanese. Follow this step:

Go to **Control Panel** > **Clock and Region**, and click **Region**.

![image](https://github.com/jnwon/VocaloidTTS/assets/35717274/b4613a93-272a-48a5-8e52-adb147126c37)
![image](https://github.com/jnwon/VocaloidTTS/assets/35717274/a3b87c21-9098-4c8c-a604-33734d88b81a)


Move to **Administrator** tap and check the **Language for non-Unicode programs**.

![image](https://github.com/jnwon/VocaloidTTS/assets/35717274/7d27624f-b7b4-41f7-add6-bf3613da5c32)


If **Current language for non-Unicode programs** is not Japanese, click **Change system locale** button and select **Japanese (Japan)**, then click OK.

![image](https://github.com/jnwon/VocaloidTTS/assets/35717274/7c01d491-a0e9-4eff-8c78-26112c8af6af)

![image](https://github.com/jnwon/VocaloidTTS/assets/35717274/97b0264f-fd2f-41e2-859d-1323720c30ae)


After you restart the Windows try Vocaloid TTS again.
